Repository Setaday/Setaday-Client, pull requests merged in 2024-11, with the labels that each got.

#62 feat(mobile): 시간 선택 View Layout을 구현합니다.
  .vscode/settings.json
  apps/mobile/app/select-date/layout.tsx
  apps/mobile/app/select-date/page.tsx
  apps/mobile/components/select-date/SelectDateHeader.tsx
  apps/mobile/styles/globals.css
Labels: ✨ feat, 📱 mobile, size/M

#71 chore(ui): 디자인 시스템 UI 패키지 export path를 수정합니다.
  .changeset/odd-laws-decide.md
  packages/ui/index.ts
  packages/ui/src/index.ts
Labels: 📝 chore, 🖌️ design-system, size/S

#74 Version Packages
  .changeset/little-olives-sleep.md
  .changeset/odd-laws-decide.md
  apps/desktop/CHANGELOG.md
  apps/desktop/package.json
  apps/mobile/CHANGELOG.md
  apps/mobile/package.json
  packages/ui/CHANGELOG.md
  packages/ui/package.json
Labels: size/M

#77 Version Packages
  .changeset/shiny-planets-rest.md
  apps/desktop/CHANGELOG.md
  apps/desktop/package.json
  apps/mobile/CHANGELOG.md
  apps/mobile/package.json
  packages/ui/CHANGELOG.md
  packages/ui/package.json
Labels: size/M

#73 bugfix: lint-staged command 오류를 수정합니다.
  apps/mobile/app/select-time/page.tsx
  apps/mobile/components/SelectTimeHeader.tsx
  biome.json
  package.json
Labels: 🐞 bugfix, size/M

#81 chore(ui): UI 컴포넌트 스타일 번들링을 추가합니다.
  .changeset/mighty-waves-own.md
  apps/mobile/package.json
  apps/mobile/tailwind.config.ts
  packages/ui/package.json
  packages/ui/src/Button/Button.styles.ts
  packages/ui/src/TextField/TextField.tsx
  packages/ui/styles/globals.css
  packages/ui/tailwind.config.ts
  pnpm-lock.yaml
Labels: size/XXL

#82 Version Packages
  .changeset/mighty-waves-own.md
  apps/desktop/CHANGELOG.md
  apps/desktop/package.json
  apps/mobile/CHANGELOG.md
  apps/mobile/package.json
  packages/ui/CHANGELOG.md
  packages/ui/package.json
Labels: size/M
