Repository Setaday/Setaday-Client, pull requests merged in 2024-12, with the labels that each got.

#83 bugfix(ui): UI 패키지 스타일 주입 오류를 수정합니다.
  .changeset/sour-clocks-smoke.md
  packages/ui/index.ts
  packages/ui/src/TextField/TextField.tsx
Labels: 🐞 bugfix, 🖌️ design-system, size/XS

#84 Version Packages
  .changeset/sour-clocks-smoke.md
  apps/desktop/CHANGELOG.md
  apps/desktop/package.json
  apps/mobile/CHANGELOG.md
  apps/mobile/package.json
  packages/ui/CHANGELOG.md
  packages/ui/package.json
Labels: size/M

#85 Version Packages
  .changeset/giant-waves-repair.md
  apps/desktop/CHANGELOG.md
  apps/desktop/package.json
  apps/mobile/CHANGELOG.md
  apps/mobile/package.json
  packages/ui/CHANGELOG.md
  packages/ui/package.json
Labels: size/M

#72 feat(mobile): 시간 선택 뷰 input을 구현합니다.
  .vscode/settings.json
  apps/mobile/app/select-date/layout.tsx
  apps/mobile/app/select-date/page.tsx
  apps/mobile/components/select-date/SelectDateHeader.tsx
  pnpm-lock.yaml
Labels: ✨ feat, 📱 mobile, size/M

#96 feat(ui): TextField에 maxLength Error 처리 로직을 추가합니다.
  .changeset/brave-zebras-cross.md
  packages/ui/src/TextField/TextField.styles.ts
  packages/ui/src/TextField/TextField.tsx
Labels: ✨ feat, 🖌️ design-system, size/M

#100 Version Packages
  .changeset/brave-zebras-cross.md
  apps/desktop/CHANGELOG.md
  apps/desktop/package.json
  apps/mobile/CHANGELOG.md
  apps/mobile/package.json
  packages/ui/CHANGELOG.md
  packages/ui/package.json
Labels: size/M

#103 feat(color): red color를 추가합니다.
  .changeset/breezy-apples-wait.md
  packages/design-token/src/color.ts
  packages/ui/src/TextField/TextField.styles.ts
  packages/ui/src/TextField/TextField.tsx
Labels: ✨ feat, 🖌️ design-system, size/S

#105 Version Packages
  .changeset/breezy-apples-wait.md
  apps/desktop/CHANGELOG.md
  apps/desktop/package.json
  apps/mobile/CHANGELOG.md
  apps/mobile/package.json
  packages/design-token/CHANGELOG.md
  packages/design-token/package.json
  packages/ui/CHANGELOG.md
  packages/ui/package.json
Labels: size/M

#104 feat(mobile): 날짜 선택 뷰 캘린더를 구현합니다.
  apps/mobile/app/select-date/page.tsx
  apps/mobile/components/select-date/SelectDateCalendar.tsx
  apps/mobile/contants/calendarConst.ts
  apps/mobile/utils/getCalendarDate.ts
  pnpm-lock.yaml
Labels: ✨ feat, 📱 mobile, size/L

#108 fix( ui): Button inputSize prop이 mobile일 시 width를 100%로 수정합니다.
  .changeset/swift-kangaroos-unite.md
  packages/ui/src/Button/Button.styles.ts
Labels: size/XS

#110 Version Packages
  .changeset/swift-kangaroos-unite.md
  apps/desktop/CHANGELOG.md
  apps/desktop/package.json
  apps/mobile/CHANGELOG.md
  apps/mobile/package.json
  packages/ui/CHANGELOG.md
  packages/ui/package.json
Labels: size/M

#111 bugfix(design-token): red token이 정상적으로 적용되지 않는 이슈를 해결합니다.
  .changeset/heavy-llamas-add.md
  packages/design-token/src/color.ts
Labels: 🐞 bugfix, 🖌️ design-system, size/XS

#112 Version Packages
  .changeset/heavy-llamas-add.md
  apps/desktop/CHANGELOG.md
  apps/desktop/package.json
  apps/mobile/CHANGELOG.md
  apps/mobile/package.json
  packages/design-token/CHANGELOG.md
  packages/design-token/package.json
  packages/ui/CHANGELOG.md
  packages/ui/package.json
Labels: size/M

#106 feat(desktop): 데스크탑 헤더를 구현합니다.
  apps/desktop/app/globals.css
  apps/desktop/app/layout.tsx
  apps/desktop/app/page.module.css
  apps/desktop/app/page.tsx
  apps/desktop/app/select-date/layout.tsx
  apps/desktop/app/select-date/page.tsx
  apps/desktop/components/Header.tsx
  apps/desktop/package.json
  apps/desktop/styles/globals.css
  apps/desktop/tailwind.config.ts
  pnpm-lock.yaml
Labels: ✨ feat, 🖥️ desktop, size/XL
